apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api
spec:
  selector:
    app.kubernetes.io/component: backend-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3080

